stages:
  - deploy

deploy:
  image: alpine:latest
  stage: deploy
  only:
    - master
  script:
    - chmod og= $SSH_PRIVATE_KEY
    - apk update && apk add openssh-client
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $TARGET "cd node-apps/Nelson/backend && git pull && npm i && pm2 restart nelson_app"
